// Consume Api
export const PERSON_ON_FAILED = 'PERSON_ON_FAILED';
export const PERSON_ON_SUCCESS = 'PERSON_ON_SUCCESS';
export const PERSON_ON_PAGE = 'PERSON_ON_PAGE';
export const PERSON_ON_LOADING_PAGE = 'PERSON_ON_LOADING_PAGE';
// Update Data
export const UPDATE_ON_SUCCESS = 'PERSON_ON_SUCCESS';
export const UPDATE_ON_FAILED = 'UPDATE_ON_FAILED';
